### ISSUE TITLE
ConfigurationManager not used anymore

### ISSUE THREAD

**Issue by gerbendv** [devtrends-org/configuration-extensions#1]
I tried to implement your package in a .NET Core 6 Functions Project. Unfortunately HostBuilderContext.Configuration is not an instance of ConfigurationManager which your package extends. It's an instance of IConfiguration. Because of this I can't use the extensions in my project.

It would be great if this package could be extended for use in .NET Core 6 Functions.

**Comment by broomfn** [comment]
I will also be targeting .NET 6, so I'm guessing this may also affect me, any update on this?

Thanks

Neil

**Comment by devtrends** [comment]
Changed the library to extend IConfiguration instead of ConfigurationManager in order to support Azure Functions. Download the 1.1.0 NuGet to see the change.

**Comment by broomfn** [comment]
Awesome :-)
